apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eezbbb3kx-nodejs
  janus-idp.io/tekton: eezbbb3kx-nodejs
  backstage.io/kubernetes-id: eezbbb3kx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eezbbb3kx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
