apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eezbbb3kx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eezbbb3kx-nodejs 
  name: eezbbb3kx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: eezbbb3kx-nodejs 
